import Head from "next/head";
import { useState } from "react";

import Layout from "@/components/Layout";
import FileUploader from "@/components/FileUploader";

const defaultPhoto = {
	name: "IMG_4985.HEIC",
	size: "3.9 MB",
	source:
		"https://images.unsplash.com/photo-1582053433976-25c00369fc93?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=512&q=80",
	information: {
		"Uploaded by": "Marie Culver",
		Created: "June 8, 2020",
		"Last modified": "June 8, 2020",
		Dimensions: "4032 x 3024",
		Resolution: "72 x 72",
	},
};

export default function UploadFile() {
	const [currentFile, setCurrentFile] = useState<any>();

	const handleResult = () => {
		console.log("uplaoded");
	};

	return (
		<>
			<Head>
				<title>Upload new Image | HEIC Converter</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<Layout>
				{/* Main content */}
				<div className="flex flex-1 items-stretch">
					<main className="flex-1 overflow-y-auto">
						<div className="mx-auto max-w-7xl px-4 pt-8 sm:px-6 lg:px-8">
							<div className="flex">
								<h1 className="flex-1 text-2xl font-bold text-gray-900">
									Transform .HEIC
								</h1>
							</div>

							{/* Gallery */}
							<section className="mt-2 pb-16" aria-labelledby="gallery-heading">
								<h2 id="gallery-heading" className="sr-only">
									New .HEIC photo
								</h2>
								<FileUploader
									currentFile={currentFile}
									setCurrentFile={setCurrentFile}
									handleResult={handleResult}
								/>
							</section>
						</div>
					</main>

					{/* Details sidebar */}
					{/* {currentFile && (
						<aside className="w-96 overflow-y-auto border-l border-gray-200 bg-white p-8 lg:block">
							<div className="space-y-6 pb-12">
								<div>
									<div className="aspect-h-7 aspect-w-10 block w-full overflow-hidden rounded-lg">
										<img
											src={currentFile.source}
											alt=""
											className="object-cover"
										/>
									</div>
									<div className="mt-4 flex items-start justify-between">
										<div>
											<h2 className="text-lg font-medium text-gray-900">
												<span className="sr-only">Details for </span>
												{currentFile.name}
											</h2>
											<p className="text-sm font-medium text-gray-500">
												{currentFile?.size}
											</p>
										</div>
									</div>
								</div>
								<div>
									<h3 className="font-medium text-gray-900">Information</h3>
									<dl className="mt-2 divide-y divide-gray-200 border-b border-t border-gray-200">
										{Object.keys(currentFile.information).map((key) => (
											<div
												key={key}
												className="flex justify-between py-3 text-sm font-medium"
											>
												<dt className="text-gray-500">{key}</dt>
												<dd className="whitespace-nowrap text-gray-900">
													{currentFile.information[key]}
												</dd>
											</div>
										))}
									</dl>
								</div>
							</div>
						</aside>
					)} */}
				</div>
			</Layout>
		</>
	);
}
